### ISSUE TITLE
Parts of Niagara airport are now magenta.

### ISSUE THREAD

**Issue by Darktower2036** [truemetro/kiag-niagara#2]
After installing the scenery, it became apparent that a large swath of the airport where cars are parked is now magenta. Is there a way to fix that?

**Comment by truemetro** [comment]
odd, could you add a screenshot? the scenery shouldn't do anything to the airport itself as of yet.

**Comment by Darktower2036** [comment]
Actually, I just noticed it at several other airports yesterday while flying. So, it can't be anything to do with your freeware. Sorry to have inadvertently connected your code to that. It may have something to do with the update, or who knows what.

**Comment by truemetro** [comment]
alright, good to know I didn't fuck anything up too badly haha.
